# Generated by Django 3.0.6 on 2022-01-12 11:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='usersessions',
            name='session_key',
            field=models.TextField(db_index=True, unique=True),
        ),
        migrations.CreateModel(
            name='PostFoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('food_name', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='foods/')),
                ('ate_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 1, 12, 20, 43, 47, 352291))),
                ('last_updated_at', models.DateTimeField(default=datetime.datetime(2022, 1, 12, 20, 43, 47, 352338))),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post_foods',
            },
        ),
    ]
