# Generated by Django 3.0.6 on 2022-01-21 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0002_auto_20220112_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfoods',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='postfoods',
            name='last_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
