# Generated by Django 3.0.6 on 2022-01-24 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0002_auto_20220112_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfoods',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='postfoods',
            name='last_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='UserAccessLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_at', models.DateTimeField(blank=True, null=True)),
                ('response_at', models.DateTimeField(blank=True, null=True)),
                ('username', models.TextField(blank=True)),
                ('user_email', models.TextField(blank=True)),
                ('request_method', models.TextField(blank=True)),
                ('request_url', models.TextField(blank=True)),
                ('referer', models.TextField(blank=True)),
                ('source_ip', models.TextField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_id', models.IntegerField(blank=True)),
                ('session_key', models.TextField(blank=True)),
                ('response_time', models.IntegerField(blank=True)),
                ('status_code', models.TextField(blank=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_access_logs',
            },
        ),
    ]
